### ISSUE TITLE
Pasting a CSV fails due to id_gen error

### ISSUE THREAD

**Issue by guitarmanvt** [soltra-adapters/adapter-csvind#5]
Steps to reproduce:
1. Adapters > CSV Indicators
2. Paste the data (see below).
3. Enter something valid in the other fields.
4. Click **Submit**

Test data:
```
title,type,description,tlp,indicator_date,confidence,producer,operator,observable_type,observable_value
TestTitle,IP Watchlist,TestDescr,AMBER,2016-01-01 00:00:00,MEDIUM,MyProducer,AND,ipv4,8.8.8.8
```

Expected behavior: The data gets uploaded successfully.

Actual behavior: Error message *The administrators have been notified of this issue. An error occurred*

Crashlog:
```
App: /adapter/csvind/upload/
Message: to_xml() got an unexpected keyword argument 'include_idgen'
Traceback (most recent call last):
  File "/usr/share/edge/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/edge/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/lib/edge/python/adapters/csvind/views.py", line 78, in upload
    return do_upload(request)
  File "/var/lib/edge/python/adapters/csvind/views.py", line 56, in do_upload
    packagefd = package_from_csv(csvstream)
  File "/var/lib/edge/python/adapters/csvind/xforms_23.py", line 137, in package_from_csv
    data = pkg.to_xml(ns_dict={namespace_data:namespace_alias},include_idgen=False,include_schemalocs=False)
TypeError: to_xml() got an unexpected keyword argument 'include_idgen'
```

**Comment by guitarmanvt** [comment]
Also get the same results with this sample file: 
```
namespace_alias=tc
namespace_data=http://threatchamp.com
head_title=ThreatChamp Latest
head_description=This is the latest data from ThreatChamp
title,description,tlp,type,indicator_date,confidence,producer,operator,observable_type,observable_value
BadStuff,Really Bad Stuff,GREEN,IP Watchlist,2014-10-01 00:0:00,Medium,ThreatChamp,AND,ipv4,10.10.10.123
BadStuff,Really Bad Stuff,GREEN,IP Watchlist,2014-10-01 00:0:00,Medium,ThreatChamp,AND,ipv4,10.10.10.234
BadStuff,More Bad Stuff,AMBER,IP Watchlist,2014-10-02 00:0:00,Medium,ThreatChamp,AND,ipv4,192.168.123.123
```
File available here: https://github.com/soltra-adapters/adapter-csvind/blob/master/csvind/test.csv

**Comment by benjamin9999** [comment]
you don't have the latest adapter

**Comment by guitarmanvt** [comment]
Tested on 0.3.5. Will re-test on 0.3.6. Thanks

**Comment by guitarmanvt** [comment]
Confirmed to work on 0.3.6 with both examples.
